# Generated by Django 4.2 on 2025-09-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_event_reminder_enabled_event_reminder_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10),
        ),
    ]
